#:schema node_modules/wrangler/config-schema.json
name = "react-example"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

[vars]
# Add non-secret environment variables here
# GOOGLE_SPREADSHEET_ID = "your-id"

# Secret environment variables should be added via the Cloudflare Dashboard or `wrangler pages secret put`
# GOOGLE_SERVICE_ACCOUNT_EMAIL
# GOOGLE_PRIVATE_KEY
